service:
  name: serverless-prisma
  app: serverless-prisma
  org: dturton

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    # SLS_DEBUG: "*"
    AWS_STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-step-functions
  - serverless-step-functions-offline
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin

functions:
  getOrder:
    handler: src/tasks/getOrder.handler
